name: .NET Build and Test

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Navigate to project directory
      run: cd path/to/your/project

    - name: Restore dependencies
      run: dotnet restore path/to/your/project

    - name: Build project
      run: dotnet build path/to/your/project --configuration Release --no-restore

    - name: Run tests
      run: dotnet test path/to/your/project --no-restore --verbosity normal

    - name: Custom script example
      run: |
        echo "Executing custom script"
        # Adicione seus comandos personalizados aqui
